/*
 * Copyright (c) 2026 European Commission
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.sprind.wallet.authenticationlogic.crypto

import android.security.keystore.KeyProperties
import okio.ByteString
import okio.ByteString.Companion.toByteString
import org.bouncycastle.jce.ECNamedCurveTable
import org.bouncycastle.jce.provider.BouncyCastleProvider
import org.sprind.wallet.businesslogic.model.UserPin
import java.math.BigInteger
import java.security.KeyFactory
import java.security.KeyPair
import java.security.SecureRandom
import java.security.Security
import java.security.spec.ECFieldFp
import java.security.spec.ECParameterSpec
import java.security.spec.ECPoint
import java.security.spec.ECPrivateKeySpec
import java.security.spec.ECPublicKeySpec
import java.security.spec.EllipticCurve
import javax.crypto.SecretKeyFactory
import javax.crypto.spec.PBEKeySpec

private const val CURVE_P256_NAME = "secp256r1"

interface PinKeyFactory {

    /**
     * Generates a random salt for use in pinKey derivation.
     */
    fun generatePinSalt(): ByteString

    /**
     * Deterministically derives a pinKey pair from the given
     * user-provided PIN and salt.
     *
     * @param pin The user-provided PIN.
     * @param salt A salt that was previously generated by [generatePinSalt].
     * @return An EC key pair derived deterministically.
     */
    fun generatePinKeys(pin: UserPin, salt: ByteString): KeyPair
}

class PinKeyFactoryImpl: PinKeyFactory {

    override fun generatePinSalt(): ByteString {
        val secureRandom = SecureRandom()
        val salt = ByteArray(16)
        secureRandom.nextBytes(salt)
        return salt.toByteString()
    }

    override fun generatePinKeys(pin: UserPin, salt: ByteString): KeyPair {
        if (Security.getProvider(BouncyCastleProvider.PROVIDER_NAME) == null) {
            // Register BouncyCastle as a security provider
            Security.addProvider(BouncyCastleProvider())
        }

        // Derive the private key bytes from PIN + Salt using PBKDF2
        val iterationCount = 120_000
        val keyLength = 256
        // PBEKeySpec copies the characters it is given, so closing the pin data only erases our
        // own array — the spec keeps a copy of the PIN that has to be cleared separately.
        val spec = pin.getAndClear().use {
            PBEKeySpec(it.chars, salt.toByteArray(), iterationCount, keyLength)
        }
        val derivedKey = try {
            val skf = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256")
            skf.generateSecret(spec).encoded
        } finally {
            spec.clearPassword()
        }

        val ecSpec = ECNamedCurveTable.getParameterSpec(CURVE_P256_NAME)

        // Convert the derived key into a valid private key scalar. BigInteger is immutable, so the
        // scalar itself cannot be erased, but the PBKDF2 output can be and no longer has to live.
        val privateKeyD = BigInteger(1, derivedKey).mod(ecSpec.n)
        derivedKey.fill(0)

        // BouncyCastle is only used for P-256 curve math. Android's Conscrypt KeyFactory
        // requires standard JCA specs and rejects org.bouncycastle.jce.spec.* specs.
        val jcaCurve = EllipticCurve(
            ECFieldFp(ecSpec.curve.field.characteristic),
            ecSpec.curve.a.toBigInteger(),
            ecSpec.curve.b.toBigInteger(),
        )
        val jcaGenerator = ECPoint(
            ecSpec.g.affineXCoord.toBigInteger(),
            ecSpec.g.affineYCoord.toBigInteger(),
        )
        val jcaSpec = ECParameterSpec(
            jcaCurve,
            jcaGenerator,
            ecSpec.n,
            ecSpec.h.toInt(),
        )

        val privateKeySpec = ECPrivateKeySpec(privateKeyD, jcaSpec)

        // Generate the private key
        val keyFactory = KeyFactory.getInstance(KeyProperties.KEY_ALGORITHM_EC)
        val privateKey = keyFactory.generatePrivate(privateKeySpec)

        // Derive the public key from the private key
        val q = ecSpec.g.multiply(privateKeyD).normalize()
        val publicKeyPoint = ECPoint(
            q.affineXCoord.toBigInteger(),
            q.affineYCoord.toBigInteger(),
        )
        val publicKeySpec = ECPublicKeySpec(publicKeyPoint, jcaSpec)
        val publicKey = keyFactory.generatePublic(publicKeySpec)

        return KeyPair(publicKey, privateKey)
    }
}
